# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc2dfe851a43e9f96a408f19b5fc9667f621663f51bd6dc59b060c4db47e00a134a57f0b3cf88c8949a6fc879b4c208ef3b7161f03d9dd78c076d300795d4553
  facebook_app_id: <%= ENV['128804141119040'] %>
  facebook_app_secret: <%= ENV['f28ac6c96cb09b3c49c4e4f391f7fd6d'] %>


test:
  secret_key_base: 3714619ed2ec54cb5dd075e30286b3967b1b7bf1e6e034b4ccb2e2564d311ba790eb0215c3321482879b3b05ae87d7ff11071e2c69a1ac2c0d30c1293bcd427a
  facebook_app_id: <%= ENV['128804141119040'] %>
  facebook_app_secret: <%= ENV['f28ac6c96cb09b3c49c4e4f391f7fd6d'] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV['128804141119040'] %>
  facebook_app_secret: <%= ENV['f28ac6c96cb09b3c49c4e4f391f7fd6d'] %>
